Repository test-fullautomation/robotframework-tutorial, pull requests merged in 2023-01, with the labels that each got.

#18 Maintenance
  100_variables_and_datatypes/doc_src/tutorial-01.robot.rst
  100_variables_and_datatypes/doc_src/tutorial-03.robot.rst
  100_variables_and_datatypes/doc_src/tutorial-04.robot.rst
  100_variables_and_datatypes/doc_src/variables_and_datatypes.rst
  100_variables_and_datatypes/libs/testimport.resource
  100_variables_and_datatypes/tutorial-01.robot.html
  100_variables_and_datatypes/tutorial-03.robot.html
  100_variables_and_datatypes/tutorial-04.robot.html
  100_variables_and_datatypes/variables_and_datatypes.html
  900_building_testsuites/doc_src/exercise-03.robot.rst
  900_building_testsuites/exercise-03/exercise-03.robot.html
  README.md
  README.rst
Labels: documentation, 0.6.0

#19 Maintenance
  900_building_testsuites/building_testsuites.html
  900_building_testsuites/doc_src/building_testsuites.rst
  900_building_testsuites/doc_src/exercise-02.robot.rst
  900_building_testsuites/doc_src/exercise-06.robot.rst
  900_building_testsuites/doc_src/exercise-07.robot.rst
  900_building_testsuites/exercise-01/exercise-01.robot
  900_building_testsuites/exercise-02/exercise-02-B.robot
  900_building_testsuites/exercise-02/exercise-02.robot
  900_building_testsuites/exercise-02/exercise-02.robot.html
  900_building_testsuites/exercise-03/exercise-03-A.robot
  900_building_testsuites/exercise-03/exercise-03-B.robot
  900_building_testsuites/exercise-03/exercise-03.robot
  900_building_testsuites/exercise-04/testsuites/__init__.robot
  900_building_testsuites/exercise-05/exercise-05.robot
  900_building_testsuites/exercise-06/exercise-06.robot
  900_building_testsuites/exercise-06/exercise-06.robot.html
  900_building_testsuites/exercise-07/config/exercise-07_config_default.json
  900_building_testsuites/exercise-07/exercise-07-B.robot
  900_building_testsuites/exercise-07/exercise-07.robot
  900_building_testsuites/exercise-07/exercise-07.robot.html
Labels: documentation, 0.6.0

#20 Hotfix
  100_variables_and_datatypes/libs/testimport.resource
Labels: documentation, 0.6.0

#21 Fixed some typing mistakes
  900_building_testsuites/building_testsuites.html
  900_building_testsuites/doc_src/building_testsuites.rst
  900_building_testsuites/doc_src/exercise-06.robot.rst
  900_building_testsuites/exercise-06/exercise-06.robot.html
Labels: enhancement, 0.6.0

#22 Explained local config mechanism in more detail in exercise-06
  900_building_testsuites/building_testsuites.html
  900_building_testsuites/doc_src/building_testsuites.rst
  900_building_testsuites/doc_src/exercise-06.robot.rst
  900_building_testsuites/exercise-06/exercise-06.robot.html
Labels: documentation, 0.6.0

#24 update robot testfiles due to renamed package
  901_static_code_analysis/suite01.robot
  901_static_code_analysis/suite02.robot
Labels: enhancement, 0.7.0

#26 Added links to exercise HTML pages in main HTML document
  900_building_testsuites/building_testsuites.html
  900_building_testsuites/doc_src/building_testsuites.rst
Labels: documentation, 0.7.0
